# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cff179280aac8965dbabade76af1fbb22632aaa41cee947ed03fd05d90f0b54dc93f922d6d8120d39d2a4443b69c7663d90c9f06db05778896eff2a4e275d2c

test:
  secret_key_base: 6b9126511c9a2fd95030516da5407ec8bffe5ee71af14b275abd3377fe512caf75a20045c73922ab0475c238cefef244017a069b81ee6d0d35bbe66967f7a388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
